name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
        with:
          go-version: 1.24.7

      - name: Build
        run: go build -v ./...

      - name: "DEBUG: What's our directory & what's in it?"
        run: pwd && ls

      - name: Build the sysinfo executables
        run: ./build-executables.sh ${{ github.event.release.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install && npx semantic-release